### ISSUE TITLE
access to sources of USDA's Onstad's EDWIP

### ISSUE THREAD

**Issue by jhpoelen** [viralemergence/insectDisease#2]
Hi ! 

As I was investigating the root causes of some suspicious interaction claims reported via https://github.com/globalbioticinteractions/globalbioticinteractions/issues/672 , I found some of the interaction records originating from a dataset derived from USDA's Onstad's EDWIP. Then, I noticed the issue you or your colleagues open at https://github.com/millerse/Ecological-Database-of-the-World-s-Insect-Pathogens/issues/5 .

I was thinking to re-index the EDWIP from their original sources and noticed that you did something similar. However, I could not find the original data source provided by Onstad. Would you happen to know where to find Onstad's original copy of the pathogen database?

**Comment by jhpoelen** [comment]
I found some references to EDWIP pointing to https://insectweb.inhs.uiuc.edu/pathogens/EDWIP/index.html , however, this URL hosted at the Illinois Natural History Survey appears to be stale. Perhaps INHS's Matt Yoder @mjy knows more about the provenance of this valuable pathogen dataset.

**Comment by taddallas** [comment]
I wish, and I honestly thought I had it. I was given a bunch of files in some proprietary database format. (already a bad sign). They were given to me by Patrick Stephens who got them directly from Onstad, as he attended one of the first meetings of our group (Macroecology of Infectious Disease RCN). But then I see published papers with virus data, and it's like...was I missing some file? Idk. It'd be nice to get to the bottom of it, but like you, I can't seem to find a good version of EDWIP online anywhere and so I have to sort of trust in the version I have that doesn't have viruses. 

Globi is probably safe using the version maintained by millerse, but the original data include failed inoculations (true negative associations) which would (hopefully) have been removed prior to the globi-fication. 

Thanks for following up on this. I am kind of curious and would like to get to the bottom of this. haha.

**Comment by mjy** [comment]
I'm clueless. My first suggestion to dig further re the now defunct site is via the wayback machine?

**Comment by jhpoelen** [comment]
@taddallas thanks for your prompt reply. Hopefully, once we get our hands on the original files, we can publish a copy of the original data in whatever format provided. Then, we have a copy to fallback to in case we'd like to redo transcriptions / transformations.

**Comment by jhpoelen** [comment]
@mjy 

https://web.archive.org/web/20170904172037/https://insectweb.inhs.uiuc.edu/pathogens/EDWIP/index.html (see attached screenshot)

![Screenshot from 2021-06-23 15-58-43](https://user-images.githubusercontent.com/1084872/123178378-ed0ad080-d43b-11eb-900c-b06ed1afaf3d.png)


points to http://cricket.inhs.illinois.edu/edwipweb/edwipabout.htm 

and that link was not archived (see https://web.archive.org/web/*/http://cricket.inhs.illinois.edu/edwipweb/edwipabout.htm) 

![Screenshot from 2021-06-23 15-59-27](https://user-images.githubusercontent.com/1084872/123178459-188dbb00-d43c-11eb-845f-aeba98df2693.png)

So . . . appears to be a dead-end ; (

Wouldn't it be nice if we'd have some infrastructure to keep decentralized immutable versioned copies of biodiversity datasets . . . something like https://preston.guoda.bio perhaps. :smile:

**Comment by jhpoelen** [comment]
Also via https://www.ent.iastate.edu/people/david-onstad I found http://disease_macroecology.ecology.uga.edu/data/ , another dead link. The page was archived via https://web.archive.org/web/20160816175115/http://disease_macroecology.ecology.uga.edu/data/  and contains text ```For access to the files contact Patrick R Stephens (prsteph at uga.edu).``` . So, it appears that we are back to a single human to provide access to the source data. 
(see screenshot below)

@taddallas any chance you can ask Patrick Stephens to send another copy of the original dataset in it's original form?

![Screenshot from 2021-06-23 16-07-40](https://user-images.githubusercontent.com/1084872/123178945-298afc00-d43d-11eb-9ea4-fd80bbf2ce31.png)

**Comment by taddallas** [comment]
I'm on it. I'll go through my hard drive backup and see if I can't find the original files (at least the csv conversions from FileMaker Pro 5 ... I think they are now on version 12 or more).

**Comment by taddallas** [comment]
Found the original files that were given to me, in filemaker pro and my converted csv files. This may still not get us to the bottom of this, as I think the insectDisease package is a true representation of what was given to me (I think I ignored some of the csv files because they seemed suspect e.g., new_asso.csv has a host "My host" which I've never heard of). 

https://github.com/taddallas/EDWIP

**Comment by jhpoelen** [comment]
@taddallas yay for backups! Thanks for publishing these original files. I have a feeling that these files might be quite valuable and suggest to add attribution / citation of their provenance to the readme. Also, I'd suggest to push a release to Zenodo to create a non-github snapshot.

**Comment by taddallas** [comment]
Right? I'm kind of proud of 2013 grad student me. Definitely a good call on releasing through Zenodo or figshare. I'll do that shortly. I think I was worried about data provenance, but I believe Onstad passed them along to be used. I also just noticed that there are new_nema associations that aren't in my nematode data.frame. I'll dig into why I opted to ignore them (some of the other "new" prefixes seem off). Thanks for the push on this. I guess we still don't actually know what's going on with the EDWIP copy that millerse has versus this much smaller version.

**Comment by jhpoelen** [comment]
i know that @millerse refers to a 2016 copy of the dataset. Would you happen to know whether the database was still under active development at that time? 

Also, in addition to the derived dataset that @millerse helped put together, I was thinking to index the sources directly using some globi schema mapping configurations. Would you be open to a pull request on your raw dataset to add some globi json ? 

 In addition, just curious - how did you go about linking the virus names with the acronyms (e.g., Spodoptera frugiperda NPV vs Spodoptera frugiperda nuclear polyhedrosis virus  vs Spodoptera frugiperda multiple nucleopolyhedrovirus [NCBI:txid10455](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=10455)) .

**Comment by taddallas** [comment]
I don't believe the database was still under development, but I'm not sure. Certainly not a 20k+ records boost development effort, right? 

I'm not averse to some globi formatting, but it seems like we should get to the bottom of the data source issue first. Don't want to have two copies (one potentially incomplete or incorrect) in there. 

In terms of any taxonomic backbone or anything, I have done nothing. The data were supplied to me in beyond raw form, and I subsequently served them pretty raw. It's something is currently under development (i.e, data cleaning and augmentation), but may take a bit due to other demands. Perhaps a good goal would be by the end of summer to have names standardized and the data a bit more structured.

**Comment by jhpoelen** [comment]
Note that the GloBI formatting would not alter the source files, just add a separate file / annotations that helps GloBI to find the repository and index the original data.

I agree that having multiple interpretations of the same source dataset might be confusing to some. And, I do find that some redundancy sometimes helps to highlight suspicious transcriptions or name mappings.  

I'd be curious to see how the non-trivial name mappings of the viruses will turn out. Perhaps by sharing the unresolved names, some interested party will magically share a method to make it happen :smile:

**Comment by jhpoelen** [comment]
:+1: Thanks for helping to keep EDWIP around for a little longer!
